### ISSUE TITLE
[Enhancement] Remove Quest Icon on Profile

### ISSUE THREAD

**Issue by BloodDragooner2** [kurulen/vencord-css-snippets#1]
Awesome CSS, thank you so much! I was wondering if you'd consider removing the quest icon when someone is playing? 
![This here](https://github.com/user-attachments/assets/cec65986-fec4-473b-981c-6252d4777d33)?

**Comment by kurulen** [comment]
I should really check GitHub more often; sorry for that 2-day wait..

This has been fixed in `20240830.07.41`!

**Comment by BloodDragooner2** [comment]
Thank you! Just saw this too, so no worries on that ^^
